config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index 
    @flats = Flat.all
  end

  def new 
    @flat = Flat.new
  end

  def strong_params
    params.require(:flat).permit(:name, :address, :description, :number_of_guests, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="container">
<h1>Add a Flat</h1>
<%= simple_form_for(@flat) do |f| %>
   <div class="form-inputs"> 
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :number_of_guests %>
    <%= f.input :price_per_night %>
   </div>
  <div class="form-actions"> 
    <%= f.button :submit, class: "btn btn-primary"%>
   </div>
<% end %>
</div>

app/views/flats/index.html.erb
<h1>Flats for Rent</h1>
<p><%= link_to "Add new flat", new_flat_path  %></p>

<div class="card-group">
  <% @flats.each do |flat| %>
  <div class="card mx-1" style="width: 18rem;">
    <div class="bg-light py-3">
    <div><%= link_to flat.name, flat_path(flat) %></div>
    <div> <%= flat.description %></div>
    <div><%= flat.address %></div>
    <div><i class="fas fa-users"> <%= flat.number_of_guests  %></i><span><i class="fas fa-euro-sign"></i><%= flat.price_per_night %></div>
    </div>
    <div><%= link_to "More Info", flat_path(flat) %></div>
  </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>